"""
Bu script denetim.py'deki BÖLÜM 4 istatistik bloğunu
optimize edilmiş versiyonla değiştirir.
"""

TARGET = "/Users/ceydakus/Desktop/anomali/2_Kural_Tabanli_Denetim/denetim.py"

new_block = (
    "# ══════════════════════════════════════════════════════════════════════════════\n"
    "# BÖLÜM 4 — İSTATİSTİK ANALİZLERİ (OPTİMİZE)\n"
    "# ══════════════════════════════════════════════════════════════════════════════\n"
    "print(\"\\n── BÖLÜM 4: İstatistik Analizler ──\")\n"
    "import time\n"
    "from scipy.stats import kendalltau\n"
    "\n"
    "# ── OPTİMİZASYON 1: Sadece forecast kombinasyonlarını filtrele ────────────\n"
    "print(\"  Forecast kombinasyonları filtreleniyor...\")\n"
    "hist[\"key\"] = list(zip(hist[\"CariKod\"], hist[\"StockKod\"]))\n"
    "df_tahmin[\"key\"] = list(zip(df_tahmin[\"cari_kod\"], df_tahmin[\"stok_kod\"]))\n"
    "gecerli_keyler = set(df_tahmin[df_tahmin[\"final_tahmin\"].fillna(0) > 0][\"key\"])\n"
    "hist_filtre = hist[hist[\"key\"].isin(gecerli_keyler)].copy()\n"
    "print(f\"  hist_filtre: {len(hist_filtre):,} satır \"\n"
    "      f\"({hist_filtre.groupby(['CariKod','StockKod']).ngroups:,} kombinasyon) \"\n"
    "      f\"/ orijinal {len(hist):,} satır\")\n"
    "\n"
    "istat_tablo[\"key\"] = list(zip(istat_tablo[\"CariKod\"], istat_tablo[\"StockKod\"]))\n"
    "istat_filtre = istat_tablo[istat_tablo[\"key\"].isin(gecerli_keyler)].copy()\n"
    "print(f\"  istat_filtre: {len(istat_filtre):,} kombinasyon\")\n"
    "\n"
    "hist_istat = hist_filtre.merge(\n"
    "    istat_filtre.drop(columns=[\"key\"]),\n"
    "    on=[\"CariKod\", \"StockKod\"], how=\"inner\"\n"
    ")\n"
    "\n"
    "# hist_90 filtreleme\n"
    "_keys_90 = list(zip(hist_90[\"CariKod\"], hist_90[\"StockKod\"]))\n"
    "_mask_90 = [k in gecerli_keyler for k in _keys_90]\n"
    "hist_90_filtre = hist_90[_mask_90].copy()\n"
    "\n"
    "# ── A) IQR Anomali (min 4 gözlem) ─────────────────────────────────────────\n"
    "print(\"  A) IQR Anomali...\", end=\" \", flush=True)\n"
    "t0 = time.time()\n"
    "gf_iqr = istat_filtre[istat_filtre[\"gozlem\"] >= 4][\n"
    "    [\"CariKod\",\"StockKod\",\"alt_sinir_iqr\",\"ust_sinir_iqr\",\"ortalama\",\"medyan\",\"std\"]\n"
    "]\n"
    "hi_iqr = hist_filtre.merge(gf_iqr, on=[\"CariKod\",\"StockKod\"], how=\"inner\")\n"
    "mask_iqr = (hi_iqr[\"ToplamMiktar\"] < hi_iqr[\"alt_sinir_iqr\"]) | \\\n"
    "           (hi_iqr[\"ToplamMiktar\"] > hi_iqr[\"ust_sinir_iqr\"])\n"
    "istat_iqr = hi_iqr[mask_iqr].copy()\n"
    "istat_iqr[\"yon\"] = istat_iqr.apply(\n"
    "    lambda r: \"Ust Sinir Asildi\" if r[\"ToplamMiktar\"] > r[\"ust_sinir_iqr\"]\n"
    "              else \"Alt Sinir Altinda\", axis=1\n"
    ")\n"
    "istat_iqr = istat_iqr[[\"CariKod\",\"StockKod\",\"Hafta\",\"ToplamMiktar\",\n"
    "    \"ortalama\",\"medyan\",\"std\",\"alt_sinir_iqr\",\"ust_sinir_iqr\",\"yon\"]]\n"
    "print(f\"-> {len(istat_iqr):,} satir [sure: {time.time()-t0:.1f}s]\")\n"
    "\n"
    "# ── B) Z-Skor + MAD (min 4 gözlem) ───────────────────────────────────────\n"
    "print(\"  B) Z-Skor + MAD...\", end=\" \", flush=True)\n"
    "t0 = time.time()\n"
    "gf_z = istat_filtre[istat_filtre[\"gozlem\"] >= 4][\n"
    "    [\"CariKod\",\"StockKod\",\"ortalama\",\"std\",\"medyan\",\"mad\"]\n"
    "]\n"
    "hi_z = hist_filtre.merge(gf_z, on=[\"CariKod\",\"StockKod\"], how=\"inner\")\n"
    "hi_z[\"z_skor\"] = np.where(hi_z[\"std\"] > 0,\n"
    "    (hi_z[\"ToplamMiktar\"] - hi_z[\"ortalama\"]) / hi_z[\"std\"], 0.0).round(4)\n"
    "hi_z[\"mod_z_skor\"] = np.where(hi_z[\"mad\"] > 0,\n"
    "    0.6745 * (hi_z[\"ToplamMiktar\"] - hi_z[\"medyan\"]) / hi_z[\"mad\"], 0.0).round(4)\n"
    "mask_z = (hi_z[\"z_skor\"].abs() > ESIK_ZSKOR) | (hi_z[\"mod_z_skor\"].abs() > ESIK_MOD_ZSKOR)\n"
    "istat_zskor = hi_z[mask_z][[\"CariKod\",\"StockKod\",\"Hafta\",\"ToplamMiktar\",\n"
    "    \"ortalama\",\"std\",\"z_skor\",\"medyan\",\"mad\",\"mod_z_skor\"]].copy()\n"
    "print(f\"-> {len(istat_zskor):,} satir [sure: {time.time()-t0:.1f}s]\")\n"
    "\n"
    "# ── C) UCL/LCL (min 4 gözlem) ────────────────────────────────────────────\n"
    "print(\"  C) UCL/LCL...\", end=\" \", flush=True)\n"
    "t0 = time.time()\n"
    "gf_ucl = istat_filtre[istat_filtre[\"gozlem\"] >= 4][\n"
    "    [\"CariKod\",\"StockKod\",\"ortalama\",\"std\",\"ucl\",\"lcl\"]\n"
    "]\n"
    "hi_ucl = hist_filtre.merge(gf_ucl, on=[\"CariKod\",\"StockKod\"], how=\"inner\")\n"
    "mask_ucl = (hi_ucl[\"ToplamMiktar\"] > hi_ucl[\"ucl\"]) | \\\n"
    "           ((hi_ucl[\"ToplamMiktar\"] < hi_ucl[\"lcl\"]) & (hi_ucl[\"lcl\"] > 0))\n"
    "istat_ucl = hi_ucl[mask_ucl].copy()\n"
    "istat_ucl[\"kontrol_durumu\"] = istat_ucl.apply(\n"
    "    lambda r: \"UCL Asildi (Ani Artis)\" if r[\"ToplamMiktar\"] > r[\"ucl\"]\n"
    "              else \"LCL Altinda (Ani Dusus)\", axis=1\n"
    ")\n"
    "istat_ucl = istat_ucl[[\"CariKod\",\"StockKod\",\"Hafta\",\"ToplamMiktar\",\n"
    "    \"ortalama\",\"std\",\"lcl\",\"ucl\",\"kontrol_durumu\"]]\n"
    "print(f\"-> {len(istat_ucl):,} satir [sure: {time.time()-t0:.1f}s]\")\n"
    "\n"
    "# ── D) CUSUM (min 8 gözlem) ───────────────────────────────────────────────\n"
    "print(\"  D) CUSUM (min 8)...\", end=\" \", flush=True)\n"
    "t0 = time.time()\n"
    "cusum_sonuclar = []\n"
    "for (cari, stok), grup in hist_filtre.groupby([\"CariKod\",\"StockKod\"]):\n"
    "    x = grup.sort_values(\"Hafta\")[\"ToplamMiktar\"].values\n"
    "    if len(x) < 8:\n"
    "        continue\n"
    "    irow = istat_filtre[(istat_filtre[\"CariKod\"]==cari) & (istat_filtre[\"StockKod\"]==stok)]\n"
    "    if irow.empty:\n"
    "        continue\n"
    "    mu  = float(irow[\"ortalama\"].values[0])\n"
    "    std = max(float(irow[\"std\"].values[0]), 1.0)\n"
    "    k = ESIK_CUSUM_K * std; h = ESIK_CUSUM_H * std\n"
    "    cp = cn = 0.0\n"
    "    for xi in x:\n"
    "        cp = max(0.0, cp + xi - mu - k)\n"
    "        cn = max(0.0, cn - xi + mu - k)\n"
    "    if cp > h:\n"
    "        cusum_sonuclar.append({\"CariKod\":cari,\"StockKod\":stok,\"alarm_tipi\":\"Artis Trendi\",\n"
    "            \"cusum_pos_son\":round(cp,2),\"cusum_neg_son\":round(cn,2),\n"
    "            \"gozlem_sayisi\":len(x),\"ortalama\":round(mu,2)})\n"
    "    elif cn > h:\n"
    "        cusum_sonuclar.append({\"CariKod\":cari,\"StockKod\":stok,\"alarm_tipi\":\"Dusus Trendi\",\n"
    "            \"cusum_pos_son\":round(cp,2),\"cusum_neg_son\":round(cn,2),\n"
    "            \"gozlem_sayisi\":len(x),\"ortalama\":round(mu,2)})\n"
    "istat_cusum = pd.DataFrame(cusum_sonuclar) if cusum_sonuclar else pd.DataFrame(\n"
    "    columns=[\"CariKod\",\"StockKod\",\"alarm_tipi\",\"cusum_pos_son\",\"cusum_neg_son\",\"gozlem_sayisi\",\"ortalama\"])\n"
    "print(f\"-> {len(istat_cusum):,} alarm [sure: {time.time()-t0:.1f}s]\")\n"
    "\n"
    "# ── E) Benford (min 30 gözlem) ────────────────────────────────────────────\n"
    "print(\"  E) Benford (min 30)...\", end=\" \", flush=True)\n"
    "t0 = time.time()\n"
    "from scipy.stats import chisquare as scipy_chisquare\n"
    "benford_beklenen = np.array([np.log10(1 + 1/d) for d in range(1,10)])\n"
    "benford_sonuclar = []\n"
    "for (cari, stok), grup in hist_filtre.groupby([\"CariKod\",\"StockKod\"]):\n"
    "    x_pos = grup[\"ToplamMiktar\"].values; x_pos = x_pos[x_pos > 0]\n"
    "    if len(x_pos) < 30:\n"
    "        continue\n"
    "    try:\n"
    "        ilk_rakam = np.array([int(str(int(abs(v)))[0]) for v in x_pos\n"
    "                              if str(int(abs(v))) and str(int(abs(v)))[0] != \"0\"])\n"
    "    except Exception:\n"
    "        continue\n"
    "    if len(ilk_rakam) < 30:\n"
    "        continue\n"
    "    gozlenen = np.array([np.sum(ilk_rakam == d) for d in range(1,10)])\n"
    "    try:\n"
    "        _, p = scipy_chisquare(gozlenen, f_exp=benford_beklenen * len(ilk_rakam))\n"
    "    except Exception:\n"
    "        continue\n"
    "    if p < ESIK_BENFORD_CHI2:\n"
    "        benford_sonuclar.append({\"CariKod\":cari,\"StockKod\":stok,\n"
    "            \"p_deger\":round(p,6),\"gozlem_sayisi\":len(x_pos),\n"
    "            \"yorum\":\"Benford uyumsuz — veri manipulasyonu suphesi\"})\n"
    "istat_benford = pd.DataFrame(benford_sonuclar) if benford_sonuclar else pd.DataFrame(\n"
    "    columns=[\"CariKod\",\"StockKod\",\"p_deger\",\"gozlem_sayisi\",\"yorum\"])\n"
    "print(f\"-> {len(istat_benford):,} supheli [sure: {time.time()-t0:.1f}s]\")\n"
    "\n"
    "# ── F) Mann-Kendall — kendalltau (min 8) ─────────────────────────────────\n"
    "print(\"  F) Mann-Kendall (kendalltau, min 8)...\", end=\" \", flush=True)\n"
    "t0 = time.time()\n"
    "\n"
    "def mann_kendall_hizli(seri):\n"
    "    idx = np.arange(len(seri))\n"
    "    tau, p_val = kendalltau(idx, seri)\n"
    "    if p_val < ESIK_MK_PVALUE:\n"
    "        trend = \"artis\" if tau > 0 else \"dusus\"\n"
    "    else:\n"
    "        trend = \"yok\"\n"
    "    return trend, round(float(p_val), 6), round(float(tau), 4)\n"
    "\n"
    "mk_sonuclar = []\n"
    "for (cari, stok), grup in hist_filtre.groupby([\"CariKod\",\"StockKod\"]):\n"
    "    x = grup.sort_values(\"Hafta\")[\"ToplamMiktar\"].values\n"
    "    if len(x) < 8:\n"
    "        continue\n"
    "    try:\n"
    "        trend, p, tau = mann_kendall_hizli(x)\n"
    "    except Exception:\n"
    "        continue\n"
    "    if trend != \"yok\":\n"
    "        ilk3 = round(float(np.mean(x[:3])), 2)\n"
    "        son3  = round(float(np.mean(x[-3:])), 2)\n"
    "        yorum = (\"Kademeli dusus — churn riski\" if trend == \"dusus\"\n"
    "                 else \"Kademeli artis — buyume firsati\")\n"
    "        mk_sonuclar.append({\"CariKod\":cari,\"StockKod\":stok,\"trend\":trend,\n"
    "            \"p_deger\":p,\"z_istatistigi\":tau,\"gozlem_sayisi\":len(x),\n"
    "            \"ilk_3_ort\":ilk3,\"son_3_ort\":son3,\"yorum\":yorum})\n"
    "istat_mk = pd.DataFrame(mk_sonuclar) if mk_sonuclar else pd.DataFrame(\n"
    "    columns=[\"CariKod\",\"StockKod\",\"trend\",\"p_deger\",\"z_istatistigi\",\n"
    "             \"gozlem_sayisi\",\"ilk_3_ort\",\"son_3_ort\",\"yorum\"])\n"
    "print(f\"-> {len(istat_mk):,} anlamli trend [sure: {time.time()-t0:.1f}s]\")\n"
    "\n"
    "# ── G) KS Testi (tarihsel>=12, son90>=3) ──────────────────────────────────\n"
    "print(\"  G) KS Testi (tarihsel>=12, son90>=3)...\", end=\" \", flush=True)\n"
    "t0 = time.time()\n"
    "ks_sonuclar = []\n"
    "for (cari, stok), grup in hist_filtre.groupby([\"CariKod\",\"StockKod\"]):\n"
    "    tarihsel = grup.sort_values(\"Hafta\")[\"ToplamMiktar\"].values\n"
    "    son90_verisi = hist_90_filtre[\n"
    "        (hist_90_filtre[\"CariKod\"]==cari) & (hist_90_filtre[\"StockKod\"]==stok)\n"
    "    ][\"ToplamMiktar\"].values\n"
    "    if len(tarihsel) < 12 or len(son90_verisi) < 3:\n"
    "        continue\n"
    "    try:\n"
    "        ks_stat, p = ks_2samp(tarihsel, son90_verisi)\n"
    "    except Exception:\n"
    "        continue\n"
    "    if p < ESIK_KS_PVALUE:\n"
    "        ort_tar = round(float(np.mean(tarihsel)), 2)\n"
    "        ort_s90 = round(float(np.mean(son90_verisi)), 2)\n"
    "        ks_sonuclar.append({\"CariKod\":cari,\"StockKod\":stok,\n"
    "            \"ks_istatistigi\":round(ks_stat,4),\"p_deger\":round(p,6),\n"
    "            \"ort_tarihsel\":ort_tar,\"ort_son90\":ort_s90,\n"
    "            \"tarihsel_gozlem\":len(tarihsel),\"son90_gozlem\":len(son90_verisi),\n"
    "            \"yorum\":\"Son donemde artis\" if ort_s90 > ort_tar else \"Son donemde dusus\"})\n"
    "istat_ks = pd.DataFrame(ks_sonuclar) if ks_sonuclar else pd.DataFrame(\n"
    "    columns=[\"CariKod\",\"StockKod\",\"ks_istatistigi\",\"p_deger\",\"ort_tarihsel\",\n"
    "             \"ort_son90\",\"tarihsel_gozlem\",\"son90_gozlem\",\"yorum\"])\n"
    "print(f\"-> {len(istat_ks):,} dagilim kaymasi [sure: {time.time()-t0:.1f}s]\")\n"
    "\n"
    "# ── H) Shannon Entropy (min 6 gözlem) ────────────────────────────────────\n"
    "print(\"  H) Shannon Entropy (min 6)...\", end=\" \", flush=True)\n"
    "t0 = time.time()\n"
    "entropy_sonuclar = []\n"
    "for (cari, stok), grup in hist_filtre.groupby([\"CariKod\",\"StockKod\"]):\n"
    "    x = grup[\"ToplamMiktar\"].values\n"
    "    if len(x) < 6:\n"
    "        continue\n"
    "    n_bins = max(10, int(np.sqrt(len(x))))\n"
    "    counts, _ = np.histogram(x, bins=n_bins)\n"
    "    counts_nz = counts[counts > 0]\n"
    "    if len(counts_nz) < 2:\n"
    "        continue\n"
    "    probs = counts_nz / counts_nz.sum()\n"
    "    raw_e = float(scipy_entropy(probs))\n"
    "    norm_e = raw_e / np.log(len(counts_nz))\n"
    "    if norm_e >= ESIK_ENTROPY_YUKSEK:\n"
    "        entropy_sonuclar.append({\"CariKod\":cari,\"StockKod\":stok,\n"
    "            \"normalize_entropy\":round(norm_e,4),\"raw_entropy\":round(raw_e,4),\n"
    "            \"gozlem_sayisi\":len(x),\"ortalama_miktar\":round(float(np.mean(x)),2),\n"
    "            \"yorum\":\"Yuksek ongorulemezerlik — tahmin guclugu\"})\n"
    "istat_entropy = pd.DataFrame(entropy_sonuclar) if entropy_sonuclar else pd.DataFrame(\n"
    "    columns=[\"CariKod\",\"StockKod\",\"normalize_entropy\",\"raw_entropy\",\n"
    "             \"gozlem_sayisi\",\"ortalama_miktar\",\"yorum\"])\n"
    "print(f\"-> {len(istat_entropy):,} yuksek entropi [sure: {time.time()-t0:.1f}s]\")\n"
    "\n"
    "# ── I) Runs Testi (min 10 gözlem) ────────────────────────────────────────\n"
    "print(\"  I) Runs Testi (min 10)...\", end=\" \", flush=True)\n"
    "t0 = time.time()\n"
    "\n"
    "def runs_manuel(x, med):\n"
    "    binary = [1 if v > med else 0 for v in x]\n"
    "    n1 = sum(binary); n0 = len(binary) - n1\n"
    "    if n0 < 1 or n1 < 1:\n"
    "        return 0.0, 1.0\n"
    "    runs = 1\n"
    "    for i in range(1, len(binary)):\n"
    "        if binary[i] != binary[i-1]:\n"
    "            runs += 1\n"
    "    mu_r  = (2*n1*n0)/(n1+n0) + 1\n"
    "    var_r = (2*n1*n0*(2*n1*n0-n1-n0)) / ((n1+n0)**2 * max(n1+n0-1, 1))\n"
    "    z = (runs - mu_r) / max(np.sqrt(var_r), 1e-9)\n"
    "    p = 2 * (1 - sp_stats.norm.cdf(abs(z)))\n"
    "    return float(z), float(p)\n"
    "\n"
    "runs_sonuclar = []\n"
    "for (cari, stok), grup in hist_filtre.groupby([\"CariKod\",\"StockKod\"]):\n"
    "    x = grup.sort_values(\"Hafta\")[\"ToplamMiktar\"].values\n"
    "    if len(x) < 10:\n"
    "        continue\n"
    "    med = float(np.median(x))\n"
    "    try:\n"
    "        if RUNS_MEVCUT:\n"
    "            z, p = runstest_1samp(x, cutoff=med)\n"
    "        else:\n"
    "            z, p = runs_manuel(x, med)\n"
    "    except Exception:\n"
    "        z, p = runs_manuel(x, med)\n"
    "    if p < ESIK_RUNS_PVALUE:\n"
    "        yorum = (\"Periyodik patern\" if float(z) < 0 else \"Kumelenme paterni\")\n"
    "        runs_sonuclar.append({\"CariKod\":cari,\"StockKod\":stok,\n"
    "            \"z_istatistigi\":round(float(z),4),\"p_deger\":round(float(p),6),\n"
    "            \"gozlem_sayisi\":len(x),\"yorum\":yorum})\n"
    "istat_runs = pd.DataFrame(runs_sonuclar) if runs_sonuclar else pd.DataFrame(\n"
    "    columns=[\"CariKod\",\"StockKod\",\"z_istatistigi\",\"p_deger\",\"gozlem_sayisi\",\"yorum\"])\n"
    "print(f\"-> {len(istat_runs):,} patern [sure: {time.time()-t0:.1f}s]\")\n"
    "\n"
    "# ── J) İstatistik Özet Tablosu ────────────────────────────────────────────\n"
    "istat_ozet = istat_filtre.drop(columns=[\"key\"], errors=\"ignore\").rename(columns={\n"
    "    \"gozlem\":\"Gozlem Sayisi\",\"ortalama\":\"Ortalama\",\"medyan\":\"Medyan\",\n"
    "    \"std\":\"Std Sapma\",\"q1\":\"Q1 (25%)\",\"q3\":\"Q3 (75%)\",\"iqr\":\"IQR\",\n"
    "    \"alt_sinir_iqr\":\"Alt Sinir (IQR)\",\"ust_sinir_iqr\":\"Ust Sinir (IQR)\",\n"
    "    \"ucl\":\"UCL (3s)\",\"lcl\":\"LCL (3s)\",\"mad\":\"MAD\",\n"
    "    \"carpiklik\":\"Carpiklik\",\"basiklik\":\"Basiklik\",\n"
    "})\n"
    "\n"
)

with open(TARGET, "r", encoding="utf-8") as f:
    lines = f.readlines()

# Bölüm 4 başlangıç satırını bul (0-indexed)
start_idx = None
end_idx = None
for i, line in enumerate(lines):
    if "# BÖLÜM 4" in line and "İSTATİSTİK" in line and start_idx is None:
        start_idx = i
    if "# BÖLÜM 5" in line and "EXCEL" in line and end_idx is None:
        end_idx = i
        break

if start_idx is None or end_idx is None:
    raise ValueError(f"Satırlar bulunamadı: start={start_idx}, end={end_idx}")

print(f"Değiştirilen satırlar: {start_idx+1} – {end_idx} (0-indexed {start_idx}–{end_idx-1})")

new_lines = lines[:start_idx] + [new_block] + lines[end_idx:]

with open(TARGET, "w", encoding="utf-8") as f:
    f.writelines(new_lines)

print(f"Bitti. Toplam satır: {len(new_lines)}")
